version: '3.7'
services:
  mongodb-standalone:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  zookeeper-standalone:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-standalone:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-standalone
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-standalone
      KAFKA_ADVERTISED_LISTENERS : LISTENER_INTERNAL://localhost:29092,LISTENER_EXTERNAL://kafka-standalone.ironsource.svc.cluster.local:9092
      KAFKA_LISTENERS: LISTENER_INTERNAL://0.0.0.0:29092,LISTENER_EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_EXTERNAL:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-standalone:2181

  customer-manager-web-server:
    image: tfrisz/customer-manager-web-server:v1.0.1
    depends_on:
      - zookeeper-standalone
      - kafka-standalone
      - mongodb-standalone
    ports:
      - "8000:8000"

  customer-facing-api:
    image: tfrisz/customer-facing-api:v1.0.4
    depends_on:
      - zookeeper-standalone
      - kafka-standalone
      - customer-manager-web-server
    ports:
      - "8001:8001"

  frontend:
    image: tfrisz/basic-store-fronted:v1.0.1
    ports:
      - "8002:80"

volumes:
  mongodb_data_container:
  grafana-data:
