apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: customer-facing-api.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customer-facing-api
            port:
              number: 8001
